set terminal png
set grid
set nokey
unset border
unset xtics

set style data histogram
set style histogram cluster gap 2
set style fill solid border -1
set boxwidth 0.4
set yrange [-100:]


set title "Figure 2: Protocol service usage 2011"
plot	"temptask3.data" using 1:(-1):2 with labels rotate right title "Service Name",\
      "temptask3.data" using 1:3 with boxes title "Percentage", "" u 1:3:3 with labels rotate right offset char 0,3
