set terminal png
set grid
set nokey
unset border
unset xtics

set style data histogram
set style histogram cluster gap 0.2
set style fill solid border -1
set boxwidth 0.4
set yrange [-100:]


set title "Figure 3: The percentage of visted web sites 2011"
plot	"temptask4.data" using 1:(-1):4 with labels rotate right title "Host Name",\
      "temptask4.data" using 1:3 with boxes title "Percentage", "" u 1:3:3 with labels rotate right offset char 0,3
